definitions:
  domain.BadRequestResponse:
    properties:
      code:
        example: "004"
        type: string
      message:
        example: '[message]'
        type: string
      result:
        example: "null"
        type: string
    type: object
  domain.ExamplePredictName:
    properties:
      name:
        example: Admin
        type: string
    type: object
  domain.InputRandomJoke:
    properties:
      is_safe:
        example: false
        type: boolean
    type: object
  domain.SuccessResponse:
    properties:
      code:
        example: "000"
        type: string
      message:
        example: '[message]'
        type: string
      result:
        type: object
    type: object
host: apigogame.herokuapp.com
info:
  contact:
    email: intanmarsjaf@outlook.com
    name: Developer
  description: This page is API documentation for a little game like predict age,
    gender by name, get random fact, image, joke
  title: GOGAME
  version: "1.0"
paths:
  /game/dare:
    get:
      description: This is API to get random activity
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Activity
      tags:
      - Game
  /game/fact:
    get:
      description: This is API to get random fact
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Fact
      tags:
      - Game
  /game/img:
    get:
      description: This is API to get random image
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Image
      tags:
      - Game
  /game/joke:
    post:
      consumes:
      - application/json
      description: This is API to get random joke
      parameters:
      - description: Body
        in: body
        name: domain.InputRandomJoke
        required: true
        schema:
          $ref: '#/definitions/domain.InputRandomJoke'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Joke
      tags:
      - Game
  /game/predict:
    post:
      consumes:
      - application/json
      description: This is API to get prediction from name input by user
      parameters:
      - description: Body
        in: body
        name: domain.ExamplePredictName
        required: true
        schema:
          $ref: '#/definitions/domain.ExamplePredictName'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Prediction By Name
      tags:
      - Game
  /master/api:
    get:
      consumes:
      - application/json
      description: This is API to get list of public API by auth or category
      parameters:
      - description: Params 1
        in: query
        name: auth
        type: boolean
      - description: Params 2
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: List Public API
      tags:
      - Master Data
  /master/country:
    get:
      consumes:
      - application/json
      description: This is API to get list country by country id or region
      parameters:
      - description: Params 1
        in: query
        name: id
        type: string
      - description: Params 2
        in: query
        name: region
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: List Country
      tags:
      - Master Data
schemes:
- https
swagger: "2.0"
