basePath: /game
definitions:
  domain.BadRequestResponse:
    properties:
      code:
        example: "004"
        type: string
      message:
        example: '[message]'
        type: string
      result:
        example: "null"
        type: string
    type: object
  domain.ExampleGameName:
    properties:
      Name:
        example: Admin
        type: string
    type: object
  domain.InputCheckJoke:
    properties:
      safe_mode:
        example: false
        type: boolean
    type: object
  domain.SuccessResponse:
    properties:
      code:
        example: "000"
        type: string
      message:
        example: '[message]'
        type: string
      result:
        type: object
    type: object
host: localhost:1111
info:
  contact:
    email: intanmarsjaf@outlook.com
    name: Developer
  description: This page is API documentation for a little game like predict age,
    gender by name, get random fact, image, joke
  title: GOGAME
  version: "1.0"
paths:
  /v1/dare:
    get:
      description: This is API to get random activity
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Activity Game
      tags:
      - Game
  /v1/fact:
    get:
      description: This is API to get random fact
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Fact Game
      tags:
      - Game
  /v1/img:
    get:
      description: This is API to get random image
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Image Game
      tags:
      - Game
  /v1/name:
    post:
      consumes:
      - application/json
      description: This is API to get random joke
      parameters:
      - description: Random Joke
        in: body
        name: Gamev1
        required: true
        schema:
          $ref: '#/definitions/domain.InputCheckJoke'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.BadRequestResponse'
      summary: Random Joke Game
      tags:
      - Game
schemes:
- http
swagger: "2.0"
